// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9FJF7_clShDCcGl6h_h-Z3OtlOBksqhI',
    appId: '1:657011371867:web:f96e419e5a20cc2c13f47e',
    messagingSenderId: '657011371867',
    projectId: 'school-management-app-3f4ed',
    authDomain: 'school-management-app-3f4ed.firebaseapp.com',
    storageBucket: 'school-management-app-3f4ed.firebasestorage.app',
    measurementId: 'G-9YFB59ZQEK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmiB3t5h4PCOpiooI4pweqMM2rYtULKEk',
    appId: '1:657011371867:android:43d449a77d57bee313f47e',
    messagingSenderId: '657011371867',
    projectId: 'school-management-app-3f4ed',
    storageBucket: 'school-management-app-3f4ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnoUZKVZbHQrBCthBh9mm3JaF3cDjRTk4',
    appId: '1:657011371867:ios:57c56739d580e7ce13f47e',
    messagingSenderId: '657011371867',
    projectId: 'school-management-app-3f4ed',
    storageBucket: 'school-management-app-3f4ed.firebasestorage.app',
    iosBundleId: 'com.example.schoolManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnoUZKVZbHQrBCthBh9mm3JaF3cDjRTk4',
    appId: '1:657011371867:ios:57c56739d580e7ce13f47e',
    messagingSenderId: '657011371867',
    projectId: 'school-management-app-3f4ed',
    storageBucket: 'school-management-app-3f4ed.firebasestorage.app',
    iosBundleId: 'com.example.schoolManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9FJF7_clShDCcGl6h_h-Z3OtlOBksqhI',
    appId: '1:657011371867:web:d35db4de539bc52613f47e',
    messagingSenderId: '657011371867',
    projectId: 'school-management-app-3f4ed',
    authDomain: 'school-management-app-3f4ed.firebaseapp.com',
    storageBucket: 'school-management-app-3f4ed.firebasestorage.app',
    measurementId: 'G-DNDWQH63W9',
  );
}
