import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Auto-generated by FlutterFire
import 'log_in_screen.dart'; // if you have a login page

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
return MaterialApp(
  debugShowCheckedModeBanner: false,
  title: 'School Management',
  theme: ThemeData(
    colorScheme: ColorScheme.fromSeed(
      seedColor: const Color.fromARGB(255, 96, 23, 206),
    ),
    useMaterial3: true,
  ),
  home: const LogInScreen(), //my log in screen
routes: {
  '/login': (context) => const LogInScreen(),
  // '/register': (context) => const RegisterScreen(), // Uncomment and import RegisterScreen when available
},
);
  }
}
